export const SETREPOSITORYLIST = "SETREPOSITORYLIST";
export const DELETEITEMFROMREPOSITORYLIST = "DELETEITEMFROMREPOSITORYLIST";
export const OPENMODAL = "OPENMODAL";
export const CLOSEMODAL = "CLOSEMODAL";
export const SETSELECTEDREPO = "SETSELECTEDREPO";
export const ADDSAVEDREPOSITORIESLIST = "ADDSAVEDREPOSITORIESLIST";
export const DELETESAVEDREPOSITORIESLIST = "DELETESAVEDREPOSITORIESLIST";
export const SEARCH = "SEARCH";
